"""añadir categoria y relacion con productos

Revision ID: 484bb8eff3fd
Revises: ded4db98d274
Create Date: 2026-01-04 20:50:11.850435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '484bb8eff3fd'
down_revision = 'ded4db98d274'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('nombre', sa.String(length=50), nullable=False),
                    sa.Column('descripcion', sa.String(
                        length=500), nullable=False),
                    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('nombre')
                    )
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('id_categoria', sa.Integer(), nullable=False))
        batch_op.create_foreign_key("productos_pk", 'categorias', [
                                    'id_categoria'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_constraint("productos_pk", type_='foreignkey')
        batch_op.drop_column('id_categoria')

    op.drop_table('categorias')
    # ### end Alembic commands ###
