"""Añadir rol y fecha creacion usuairo

Revision ID: 930adba066ef
Revises: f5a523b6026e
Create Date: 2025-12-22 23:23:46.100145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '930adba066ef'
down_revision = 'f5a523b6026e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column(column_name="correo", existing_type=sa.String(
        ), type_=sa.String(length=120), existing_nullable=False)
        batch_op.add_column(
            sa.Column('rol', sa.String(length=20), nullable=True))
        batch_op.add_column(
            sa.Column('fecha_creacion', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column(column_name="correo", existing_type=sa.String(
            120), type_=sa.String(), existing_nullable=False)
        batch_op.drop_column('fecha_creacion')
        batch_op.drop_column('rol')

    # ### end Alembic commands ###
