"""Modificar campos nullables

Revision ID: ded4db98d274
Revises: eb221299c180
Create Date: 2026-01-01 17:30:05.480560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ded4db98d274'
down_revision = 'eb221299c180'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('descripcion',
                              existing_type=sa.VARCHAR(length=500),
                              nullable=False)
        batch_op.alter_column('img_url',
                              existing_type=sa.VARCHAR(length=500),
                              nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('img_url',
                              existing_type=sa.VARCHAR(length=500),
                              nullable=True)
        batch_op.alter_column('descripcion',
                              existing_type=sa.VARCHAR(length=500),
                              nullable=True)

    # ### end Alembic commands ###
