"""Creación tabla productos faltante

Revision ID: eb221299c180
Revises: 930adba066ef
Create Date: 2025-12-29 18:59:35.286168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb221299c180'
down_revision = '930adba066ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('nombre', sa.String(length=50), nullable=False),
                    sa.Column('descripcion', sa.String(
                        length=500), nullable=True),
                    sa.Column('precio', sa.DECIMAL(
                        precision=10, scale=2), nullable=False),
                    sa.Column('stock', sa.Integer(), nullable=False),
                    sa.Column('img_url', sa.String(length=500), nullable=True),
                    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productos')
    # ### end Alembic commands ###
